name: "Dev deploy"

on:
  workflow_run:
    workflows: ["Build"]
    types:
        - completed

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev
    env:
      environmentPrefix: teach-fe-dev
      location: westeurope
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az group create --location ${{ env.location }} --name ${{ env.environmentPrefix }}-as-terraform
            echo "Resource group created"

            az storage account create --name ${{ parameters.environmentPrefix }}storagetf --resource-group ${{ env.environmentPrefix }}-as-terraform --location ${{ env.location }} --sku Standard_LRS
            echo "Storage account created"

            az storage container create --auth-mode login --name tfstate --account-name ${{ parameters.environmentPrefix }}storagetf
            echo "Storage container created"