name: "Dev deploy"

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ publish-event ]



jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Installing dependencies
        run: npm ci

      - name: Building Gatsby site
        run: npm run build --log-pages
        env:
          GOOGLE_ANALYTICS_TAG: ${{ secrets.GOOGLE_ANALYTICS_TAG }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          CI: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
              public
              !public/webpack.stats.json

  create-infrastructure:
    defaults:
      run:
        working-directory: "/infrastructure"
    name: "Create infrastructure"
    needs: build
    environment: Development
    env:
      env: dev
      environmentPrefix: teach-fe-dev
      location: westeurope

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --location ${{ env.location }} --name ${{ env.environmentPrefix }}-as-terraform
            echo "Resource group created for env ${{ env.env }}"

            az storage account create --name ${{ env.env }}storagetf --resource-group ${{ env.environmentPrefix }}-as-terraform --location ${{ env.location }} --sku Standard_LRS
            echo "Storage account created for env ${{ env.env }}"

            az storage container create --auth-mode login --name tfstate --account-name ${{ job.environment }}storagetf
            echo "Storage container created for env ${{ env.env }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          TF_ENVIRONMENT: ${{ env.env }}
          TF_LOCATION: ${{ env.location }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -auto-approve
