name: e2eTestsOnDev

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
   tests:
    name: e2e tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: dotnet build --configuration Debug --no-restore
      - name: Test with the dotnet CLI
        run: dotnet test --no-restore