name: e2eTestsOnDev

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  tests:
    name: e2e tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: spec\e2e\e2eTests\E2eTests.csproj
