name: e2eTests - test env

on:
  workflow_dispatch:
  pull_request:
    branches: [ test ]

jobs:
   tests:
    name: e2e tests
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: dotnet build spec/e2e/TeachFeProject.sln
      - name: Test with the dotnet CLI
        run: dotnet test spec/e2e/e2eTests/E2eTests.csproj --filter UserJourneyDev